# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detectImperfectIR_cpp <- function(enc1, enc2, minLen, maxLen, maxMismcNum, maxLoopLen = 0L) {
    .Call('detectIR_detectImperfectIR_cpp', PACKAGE = 'detectIR', enc1, enc2, minLen, maxLen, maxMismcNum, maxLoopLen)
}

rcpp_hello_world <- function() {
    .Call('detectIR_rcpp_hello_world', PACKAGE = 'detectIR')
}

