# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detectImperfectIR_cpp <- function(enc1, enc2, minStemLen, maxMismcNum, verbose = FALSE) {
    .Call('detectIR_detectImperfectIR_cpp', PACKAGE = 'detectIR', enc1, enc2, minStemLen, maxMismcNum, verbose)
}

detectImperfectIRWithLoop_cpp <- function(enc1, enc2, minStemLen, maxMismcNum, loopLength, verbose = FALSE) {
    .Call('detectIR_detectImperfectIRWithLoop_cpp', PACKAGE = 'detectIR', enc1, enc2, minStemLen, maxMismcNum, loopLength, verbose)
}

findAllowedPatches <- function(seq, minLen) {
    .Call('detectIR_findAllowedPatches', PACKAGE = 'detectIR', seq, minLen)
}

